CREATE SCHEMA IF NOT EXISTS topo;

CREATE TABLE IF NOT EXISTS topo.simulation (
  simulation_uuid uuid PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text,
  config jsonb NOT NULL,
  status text NOT NULL DEFAULT 'finished',
  CHECK (status IN ('created', 'running', 'finished', 'failed'))
);

CREATE INDEX IF NOT EXISTS ix_simulation_created_at
  ON topo.simulation(created_at);

CREATE TABLE IF NOT EXISTS topo.node (
  simulation_uuid uuid NOT NULL
    REFERENCES topo.simulation(simulation_uuid) ON DELETE CASCADE,

  node_id integer NOT NULL,
  node_uuid uuid NOT NULL,
  node_type text NOT NULL,
  name text,
  net_id integer,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, node_id),
  UNIQUE (simulation_uuid, node_uuid),

  CHECK (node_id >= 0),
  CHECK (node_type IN (
    'CGS',
    'Target',
    'Satellite',
    'HAPS',
    'Ray',
    'VSAT',
    'ImportantPlace',
    'Region'
  ))
);

CREATE INDEX IF NOT EXISTS ix_node_type
  ON topo.node(simulation_uuid, node_type);

CREATE INDEX IF NOT EXISTS ix_node_net
  ON topo.node(simulation_uuid, net_id);

CREATE TABLE IF NOT EXISTS topo.simulation_time (
  simulation_uuid uuid NOT NULL
    REFERENCES topo.simulation(simulation_uuid) ON DELETE CASCADE,

  time_index integer NOT NULL,
  time_msec bigint NOT NULL,

  PRIMARY KEY (simulation_uuid, time_index),
  CHECK (time_index >= 0)
);

CREATE TABLE IF NOT EXISTS topo.node_position (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  time_index integer NOT NULL,

  x double precision NOT NULL,
  y double precision NOT NULL,
  z double precision NOT NULL,

  PRIMARY KEY (simulation_uuid, node_id, time_index),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (time_index >= 0)
);

CREATE TABLE IF NOT EXISTS topo.edge (
  simulation_uuid uuid NOT NULL
    REFERENCES topo.simulation(simulation_uuid) ON DELETE CASCADE,

  edge_id bigint GENERATED BY DEFAULT AS IDENTITY,
  time_index integer NOT NULL,
  begin_node_id integer NOT NULL,
  end_node_id integer NOT NULL,
  edge_type text NOT NULL,
  is_bidirectional boolean NOT NULL DEFAULT false,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, edge_id),

  FOREIGN KEY (simulation_uuid, begin_node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (simulation_uuid, end_node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (time_index >= 0),
  CHECK (begin_node_id >= 0),
  CHECK (end_node_id >= 0),
  CHECK (begin_node_id <> end_node_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_edge_no_dupes
ON topo.edge(
  simulation_uuid,
  time_index,
  edge_type,
  (CASE
     WHEN is_bidirectional THEN LEAST(begin_node_id, end_node_id)
     ELSE begin_node_id
   END),
  (CASE
     WHEN is_bidirectional THEN GREATEST(begin_node_id, end_node_id)
     ELSE end_node_id
   END),
  is_bidirectional
);

CREATE INDEX IF NOT EXISTS ix_edge_time
  ON topo.edge(simulation_uuid, time_index);

CREATE INDEX IF NOT EXISTS ix_edge_begin
  ON topo.edge(simulation_uuid, begin_node_id, time_index);

CREATE INDEX IF NOT EXISTS ix_edge_end
  ON topo.edge(simulation_uuid, end_node_id, time_index);

CREATE INDEX IF NOT EXISTS ix_edge_type
  ON topo.edge(simulation_uuid, edge_type, time_index);

CREATE TABLE IF NOT EXISTS topo.connected_ray (
  simulation_uuid uuid NOT NULL
    REFERENCES topo.simulation(simulation_uuid) ON DELETE CASCADE,

  ray_node_id integer NOT NULL,
  time_index integer NOT NULL,
  origin_node_id integer NOT NULL,
  origin_node_type text NOT NULL DEFAULT 'unknown',
  ray_kind text NOT NULL DEFAULT 'unknown',
  cluster_id integer NOT NULL,
  frequency_id integer NOT NULL,
  aperture double precision NOT NULL DEFAULT 0,
  connect_count integer NOT NULL DEFAULT 0,
  target_node_id integer,
  elevation double precision NOT NULL,
  length double precision NOT NULL,
  alt double precision NOT NULL,
  beam_target_offset_rad double precision,
  pointing_x double precision,
  pointing_y double precision,
  pointing_z double precision,
  k double precision NOT NULL DEFAULT 0.0,

  PRIMARY KEY (simulation_uuid, ray_node_id, time_index),

  FOREIGN KEY (simulation_uuid, ray_node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, origin_node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (time_index >= 0)
);

CREATE INDEX IF NOT EXISTS ix_connected_ray_time
  ON topo.connected_ray(simulation_uuid, time_index);

CREATE INDEX IF NOT EXISTS ix_connected_ray_origin
  ON topo.connected_ray(simulation_uuid, origin_node_id, time_index);

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS origin_node_type text NOT NULL DEFAULT 'unknown';

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS ray_kind text NOT NULL DEFAULT 'unknown';

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS aperture double precision NOT NULL DEFAULT 0;

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS connect_count integer NOT NULL DEFAULT 0;

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS target_node_id integer;

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS beam_target_offset_rad double precision;

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS pointing_x double precision;

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS pointing_y double precision;

ALTER TABLE topo.connected_ray
  ADD COLUMN IF NOT EXISTS pointing_z double precision;

CREATE TABLE IF NOT EXISTS topo.region (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  region_code integer NOT NULL,

  PRIMARY KEY (simulation_uuid, node_id),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS topo.vsat (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  region_code integer,
  la double precision NOT NULL,
  lo double precision NOT NULL,
  alt double precision NOT NULL,

  PRIMARY KEY (simulation_uuid, node_id),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS topo.ray (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  origin_node_id integer NOT NULL,
  ray_kind text NOT NULL,
  cluster_id integer NOT NULL,
  frequency_id integer NOT NULL,
  aperture double precision NOT NULL DEFAULT 0,
  connect_limit integer,

  PRIMARY KEY (simulation_uuid, node_id),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, origin_node_id)
    REFERENCES topo.node(simulation_uuid, node_id)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS topo.topology_snapshot (
  simulation_uuid uuid NOT NULL
    REFERENCES topo.simulation(simulation_uuid) ON DELETE CASCADE,

  time_index integer NOT NULL,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, time_index),

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (time_index >= 0)
);

CREATE INDEX IF NOT EXISTS ix_topology_snapshot_time
  ON topo.topology_snapshot(simulation_uuid, time_index);


CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE IF NOT EXISTS inventory.gateway_node (
  set_key text NOT NULL,
  external_id text NOT NULL,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  site_alt_m double precision,
  antenna_height_agl_m double precision,
  radio_profile text,
  role text NOT NULL DEFAULT 'gateway',
  limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ordinal integer NOT NULL DEFAULT 0,
  PRIMARY KEY (set_key, external_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_gateway_set
  ON inventory.gateway_node(set_key, ordinal, external_id);

CREATE TABLE IF NOT EXISTS inventory.target_hub (
  set_key text NOT NULL,
  external_id text NOT NULL,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  frequency integer NOT NULL,
  priority double precision NOT NULL DEFAULT 0.0,
  site_alt_m double precision,
  antenna_height_agl_m double precision,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ordinal integer NOT NULL DEFAULT 0,
  PRIMARY KEY (set_key, external_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_target_set
  ON inventory.target_hub(set_key, ordinal, external_id);

CREATE TABLE IF NOT EXISTS inventory.satellite_node (
  set_key text NOT NULL,
  external_id text NOT NULL,
  name text NOT NULL,
  tle_line1 text NOT NULL,
  tle_line2 text NOT NULL,
  radio_profile text,
  connection_min integer NOT NULL DEFAULT 2,
  beam_layout_mode text NOT NULL DEFAULT 'free',
  dynamic_ray_count integer NOT NULL DEFAULT 16,
  dynamic_ray_aperture_deg double precision NOT NULL DEFAULT 1.5,
  sat_haps_ray_count integer NOT NULL DEFAULT 4,
  resource_limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  allowed_link_types jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ordinal integer NOT NULL DEFAULT 0,
  PRIMARY KEY (set_key, external_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_satellite_set
  ON inventory.satellite_node(set_key, ordinal, external_id);

CREATE TABLE IF NOT EXISTS inventory.haps_node (
  set_key text NOT NULL,
  external_id text NOT NULL,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  alt_m double precision NOT NULL,
  radio_profile text,
  connection_min integer NOT NULL DEFAULT 0,
  resource_limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ordinal integer NOT NULL DEFAULT 0,
  PRIMARY KEY (set_key, external_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_haps_set
  ON inventory.haps_node(set_key, ordinal, external_id);

CREATE TABLE IF NOT EXISTS inventory.vsat_node (
  set_key text NOT NULL,
  external_id text NOT NULL,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  region_code integer NOT NULL,
  site_alt_m double precision,
  antenna_height_agl_m double precision,
  radio_profile text,
  role text NOT NULL DEFAULT 'vsat',
  limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ordinal integer NOT NULL DEFAULT 0,
  PRIMARY KEY (set_key, external_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_vsat_set
  ON inventory.vsat_node(set_key, ordinal, external_id);
