CREATE SCHEMA IF NOT EXISTS topo_v2;

CREATE TABLE IF NOT EXISTS topo_v2.simulation (
  simulation_uuid uuid PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text,
  config jsonb NOT NULL,
  status text NOT NULL DEFAULT 'finished',
  CHECK (status IN ('created', 'running', 'finished', 'failed'))
);

CREATE INDEX IF NOT EXISTS ix_topo_v2_simulation_created_at
  ON topo_v2.simulation(created_at);

CREATE TABLE IF NOT EXISTS topo_v2.node (
  simulation_uuid uuid NOT NULL
    REFERENCES topo_v2.simulation(simulation_uuid) ON DELETE CASCADE,

  node_id integer NOT NULL,
  node_uuid uuid NOT NULL,
  node_type text NOT NULL,
  name text,
  net_id integer,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, node_id),
  UNIQUE (simulation_uuid, node_uuid),

  CHECK (node_id >= 0),
  CHECK (node_type IN (
    'CGS',
    'Target',
    'Satellite',
    'HAPS',
    'Ray',
    'VSAT',
    'TheoreticalSubscriber',
    'ImportantPlace',
    'Region'
  ))
);

CREATE INDEX IF NOT EXISTS ix_topo_v2_node_type
  ON topo_v2.node(simulation_uuid, node_type);

CREATE INDEX IF NOT EXISTS ix_topo_v2_node_net
  ON topo_v2.node(simulation_uuid, net_id);

CREATE TABLE IF NOT EXISTS topo_v2.simulation_time (
  simulation_uuid uuid NOT NULL
    REFERENCES topo_v2.simulation(simulation_uuid) ON DELETE CASCADE,

  time_index integer NOT NULL,
  time_msec bigint NOT NULL,

  PRIMARY KEY (simulation_uuid, time_index),
  CHECK (time_index >= 0)
);

CREATE TABLE IF NOT EXISTS topo_v2.node_position (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  time_index integer NOT NULL,

  x double precision NOT NULL,
  y double precision NOT NULL,
  z double precision NOT NULL,

  PRIMARY KEY (simulation_uuid, node_id, time_index),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo_v2.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (time_index >= 0)
);

CREATE TABLE IF NOT EXISTS topo_v2.edge (
  simulation_uuid uuid NOT NULL
    REFERENCES topo_v2.simulation(simulation_uuid) ON DELETE CASCADE,

  edge_id bigint GENERATED BY DEFAULT AS IDENTITY,
  time_index integer NOT NULL,
  begin_node_id integer NOT NULL,
  end_node_id integer NOT NULL,
  edge_type text NOT NULL,
  is_bidirectional boolean NOT NULL DEFAULT false,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, edge_id),

  FOREIGN KEY (simulation_uuid, begin_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (simulation_uuid, end_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo_v2.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (time_index >= 0),
  CHECK (begin_node_id >= 0),
  CHECK (end_node_id >= 0),
  CHECK (begin_node_id <> end_node_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_topo_v2_edge_no_dupes
ON topo_v2.edge(
  simulation_uuid,
  time_index,
  edge_type,
  (CASE
     WHEN is_bidirectional THEN LEAST(begin_node_id, end_node_id)
     ELSE begin_node_id
   END),
  (CASE
     WHEN is_bidirectional THEN GREATEST(begin_node_id, end_node_id)
     ELSE end_node_id
   END),
  is_bidirectional
);

CREATE INDEX IF NOT EXISTS ix_topo_v2_edge_time
  ON topo_v2.edge(simulation_uuid, time_index);

CREATE INDEX IF NOT EXISTS ix_topo_v2_edge_begin
  ON topo_v2.edge(simulation_uuid, begin_node_id, time_index);

CREATE INDEX IF NOT EXISTS ix_topo_v2_edge_end
  ON topo_v2.edge(simulation_uuid, end_node_id, time_index);

CREATE INDEX IF NOT EXISTS ix_topo_v2_edge_type
  ON topo_v2.edge(simulation_uuid, edge_type, time_index);

CREATE TABLE IF NOT EXISTS topo_v2.connected_ray (
  simulation_uuid uuid NOT NULL
    REFERENCES topo_v2.simulation(simulation_uuid) ON DELETE CASCADE,

  ray_node_id integer NOT NULL,
  time_index integer NOT NULL,
  origin_node_id integer NOT NULL,
  origin_node_type text NOT NULL DEFAULT 'unknown',
  ray_kind text NOT NULL DEFAULT 'unknown',
  cluster_id integer NOT NULL,
  frequency_id integer NOT NULL,
  aperture double precision NOT NULL DEFAULT 0,
  connect_count integer NOT NULL DEFAULT 0,
  target_node_id integer,
  elevation double precision NOT NULL,
  length double precision NOT NULL,
  alt double precision NOT NULL,
  beam_target_offset_rad double precision,
  pointing_x double precision,
  pointing_y double precision,
  pointing_z double precision,
  k double precision NOT NULL DEFAULT 0.0,

  PRIMARY KEY (simulation_uuid, ray_node_id, time_index),

  FOREIGN KEY (simulation_uuid, ray_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, origin_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo_v2.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (time_index >= 0)
);

CREATE INDEX IF NOT EXISTS ix_topo_v2_connected_ray_time
  ON topo_v2.connected_ray(simulation_uuid, time_index);

CREATE INDEX IF NOT EXISTS ix_topo_v2_connected_ray_origin
  ON topo_v2.connected_ray(simulation_uuid, origin_node_id, time_index);

CREATE TABLE IF NOT EXISTS topo_v2.region (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  region_code integer NOT NULL,

  PRIMARY KEY (simulation_uuid, node_id),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS topo_v2.vsat (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  region_code integer,
  la double precision NOT NULL,
  lo double precision NOT NULL,
  alt double precision NOT NULL,

  PRIMARY KEY (simulation_uuid, node_id),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS topo_v2.theoretical_subscriber (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  subscriber_key text NOT NULL,
  subject_code integer NOT NULL,
  subject_name text NOT NULL,
  federal_district text NOT NULL,
  grid_cell_id text NOT NULL,
  seed_version text NOT NULL,
  la double precision NOT NULL,
  lo double precision NOT NULL,
  alt double precision NOT NULL,
  site_alt_m double precision,
  antenna_height_agl_m double precision NOT NULL,
  radio_profile text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, node_id),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS topo_v2.theoretical_subscriber_service (
  simulation_uuid uuid NOT NULL
    REFERENCES topo_v2.simulation(simulation_uuid) ON DELETE CASCADE,

  subscriber_node_id integer NOT NULL,
  time_index integer NOT NULL,
  service_rank integer NOT NULL DEFAULT 0,
  connected boolean NOT NULL DEFAULT false,
  is_primary boolean NOT NULL DEFAULT false,
  provider_node_id integer,
  provider_type text,
  ray_node_id integer,
  ray_origin_node_id integer,
  ray_origin_type text,
  target_node_id integer,
  frequency_id integer,
  aperture_rad double precision,
  path_length_km double precision,
  beam_target_offset_rad double precision,
  radio_profile text NOT NULL,
  site_alt_m double precision,
  antenna_height_agl_m double precision,
  spectral_efficiency_bps_hz double precision,
  capacity_mbps double precision,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, subscriber_node_id, time_index, service_rank),

  FOREIGN KEY (simulation_uuid, subscriber_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo_v2.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_topo_v2_theoretical_subscriber_service_time
  ON topo_v2.theoretical_subscriber_service(simulation_uuid, time_index);

CREATE INDEX IF NOT EXISTS ix_topo_v2_theoretical_subscriber_service_provider
  ON topo_v2.theoretical_subscriber_service(simulation_uuid, provider_node_id, time_index);

CREATE TABLE IF NOT EXISTS topo_v2.link_budget_input_snapshot (
  simulation_uuid uuid NOT NULL
    REFERENCES topo_v2.simulation(simulation_uuid) ON DELETE CASCADE,

  endpoint_node_id integer NOT NULL,
  time_index integer NOT NULL,
  segment_kind text NOT NULL,
  endpoint_kind text NOT NULL,
  relay_node_id integer NOT NULL,
  relay_type text NOT NULL,
  gateway_node_id integer,
  ray_node_id integer,
  target_node_id integer,
  input_payload jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, endpoint_node_id, time_index, segment_kind),

  FOREIGN KEY (simulation_uuid, endpoint_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, relay_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo_v2.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (segment_kind IN (
    'user_downlink',
    'user_uplink',
    'feeder_downlink',
    'feeder_uplink',
    'end_to_end_forward',
    'end_to_end_return'
  ))
);

CREATE INDEX IF NOT EXISTS ix_topo_v2_link_budget_input_snapshot_time
  ON topo_v2.link_budget_input_snapshot(simulation_uuid, time_index, segment_kind);

CREATE TABLE IF NOT EXISTS topo_v2.link_budget_result (
  simulation_uuid uuid NOT NULL
    REFERENCES topo_v2.simulation(simulation_uuid) ON DELETE CASCADE,

  endpoint_node_id integer NOT NULL,
  time_index integer NOT NULL,
  segment_kind text NOT NULL,
  endpoint_kind text NOT NULL,
  relay_node_id integer NOT NULL,
  relay_type text NOT NULL,
  gateway_node_id integer,
  ray_node_id integer,
  target_node_id integer,
  available boolean NOT NULL DEFAULT false,
  reason text NOT NULL DEFAULT 'UNAVAILABLE',
  slant_range_km double precision,
  elevation_deg double precision,
  beam_target_offset_rad double precision,
  radial_velocity_mps double precision,
  doppler_hz double precision,
  lfsl_db double precision,
  lrain_db double precision,
  latm_gas_db double precision,
  latm_cloud_db double precision,
  lscint_db double precision,
  r001_mm_h double precision,
  noise_temperature_k double precision,
  cn_db double precision,
  cn0_dbhz double precision,
  ebn0_db double precision,
  spectral_efficiency_bps_hz double precision,
  info_rate_kbps double precision,
  symbol_rate_kbaud double precision,
  modcod text,
  margin_db double precision,
  profile_keys jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, endpoint_node_id, time_index, segment_kind),

  FOREIGN KEY (simulation_uuid, endpoint_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, relay_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE RESTRICT,

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo_v2.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (segment_kind IN (
    'user_downlink',
    'user_uplink',
    'feeder_downlink',
    'feeder_uplink',
    'end_to_end_forward',
    'end_to_end_return'
  ))
);

CREATE INDEX IF NOT EXISTS ix_topo_v2_link_budget_result_time
  ON topo_v2.link_budget_result(simulation_uuid, time_index, segment_kind);

CREATE INDEX IF NOT EXISTS ix_topo_v2_link_budget_result_endpoint
  ON topo_v2.link_budget_result(simulation_uuid, endpoint_node_id, time_index);

CREATE TABLE IF NOT EXISTS topo_v2.ray (
  simulation_uuid uuid NOT NULL,
  node_id integer NOT NULL,
  origin_node_id integer NOT NULL,
  ray_kind text NOT NULL,
  cluster_id integer NOT NULL,
  frequency_id integer NOT NULL,
  aperture double precision NOT NULL DEFAULT 0,
  connect_limit integer,

  PRIMARY KEY (simulation_uuid, node_id),

  FOREIGN KEY (simulation_uuid, node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE CASCADE,

  FOREIGN KEY (simulation_uuid, origin_node_id)
    REFERENCES topo_v2.node(simulation_uuid, node_id)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS topo_v2.topology_snapshot (
  simulation_uuid uuid NOT NULL
    REFERENCES topo_v2.simulation(simulation_uuid) ON DELETE CASCADE,

  time_index integer NOT NULL,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (simulation_uuid, time_index),

  FOREIGN KEY (simulation_uuid, time_index)
    REFERENCES topo_v2.simulation_time(simulation_uuid, time_index)
    ON DELETE CASCADE,

  CHECK (time_index >= 0)
);

CREATE INDEX IF NOT EXISTS ix_topo_v2_topology_snapshot_time
  ON topo_v2.topology_snapshot(simulation_uuid, time_index);


CREATE SCHEMA IF NOT EXISTS inventory_v2;

CREATE TABLE IF NOT EXISTS inventory_v2.selection_catalog (
  catalog_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  catalog_key text NOT NULL,
  name text,
  description text,
  source_type text NOT NULL DEFAULT 'manual',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  UNIQUE (kind, catalog_key),
  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers'))
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_catalog_kind_key
  ON inventory_v2.selection_catalog(kind, catalog_key);

CREATE TABLE IF NOT EXISTS inventory_v2.gateway (
  gateway_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gateway_key text NOT NULL UNIQUE,
  fingerprint_sha1 text NOT NULL UNIQUE,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  site_alt_m double precision,
  antenna_height_agl_m double precision,
  radio_profile text,
  ground_terminal_profile_key text,
  role text NOT NULL DEFAULT 'gateway',
  limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS inventory_v2.target (
  target_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_key text NOT NULL UNIQUE,
  fingerprint_sha1 text NOT NULL UNIQUE,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  frequency integer NOT NULL,
  priority double precision NOT NULL DEFAULT 0.0,
  site_alt_m double precision,
  antenna_height_agl_m double precision,
  ground_terminal_profile_key text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS inventory_v2.satellite (
  satellite_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  satellite_key text NOT NULL UNIQUE,
  fingerprint_sha1 text NOT NULL UNIQUE,
  name text NOT NULL,
  tle_line1 text NOT NULL,
  tle_line2 text NOT NULL,
  radio_profile text,
  user_beam_profile_key text,
  feeder_beam_profile_key text,
  connection_min integer NOT NULL DEFAULT 2,
  beam_layout_mode text NOT NULL DEFAULT 'free',
  dynamic_ray_count integer NOT NULL DEFAULT 16,
  dynamic_ray_aperture_deg double precision NOT NULL DEFAULT 1.5,
  sat_haps_ray_count integer NOT NULL DEFAULT 4,
  resource_limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  allowed_link_types jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS inventory_v2.haps (
  haps_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  haps_key text NOT NULL UNIQUE,
  fingerprint_sha1 text NOT NULL UNIQUE,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  alt_m double precision NOT NULL,
  radio_profile text,
  user_beam_profile_key text,
  feeder_beam_profile_key text,
  connection_min integer NOT NULL DEFAULT 0,
  resource_limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS inventory_v2.vsat (
  vsat_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vsat_key text NOT NULL UNIQUE,
  fingerprint_sha1 text NOT NULL UNIQUE,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  region_code integer NOT NULL,
  site_alt_m double precision,
  antenna_height_agl_m double precision,
  radio_profile text,
  ground_terminal_profile_key text,
  role text NOT NULL DEFAULT 'vsat',
  limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS inventory_v2.theoretical_subscriber (
  theoretical_subscriber_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_key text NOT NULL UNIQUE,
  fingerprint_sha1 text NOT NULL UNIQUE,
  name text NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  site_alt_m double precision,
  subject_code integer NOT NULL,
  subject_name text NOT NULL,
  federal_district text NOT NULL,
  grid_cell_id text NOT NULL,
  seed_version text NOT NULL,
  ground_terminal_profile_key text,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS inventory_v2.ground_terminal_profile (
  ground_terminal_profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_key text NOT NULL UNIQUE,
  station_kind text NOT NULL,
  params jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS inventory_v2.relay_payload_profile (
  relay_payload_profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_key text NOT NULL UNIQUE,
  relay_mode text NOT NULL DEFAULT 'transparent_relay',
  params jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS inventory_v2.profile_assignment_rule (
  rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_key text NOT NULL UNIQUE,
  name text NOT NULL,
  kind text NOT NULL,
  catalog_key text,
  query text,
  bbox jsonb NOT NULL DEFAULT '{}'::jsonb,
  region_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  subject_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  federal_districts jsonb NOT NULL DEFAULT '[]'::jsonb,
  grid_cell_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active_filter boolean,
  ground_terminal_profile_key text,
  user_beam_profile_key text,
  feeder_beam_profile_key text,
  priority integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers')),
  CHECK (
    ground_terminal_profile_key IS NOT NULL
    OR user_beam_profile_key IS NOT NULL
    OR feeder_beam_profile_key IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_profile_assignment_rule_active
  ON inventory_v2.profile_assignment_rule(is_active, kind, priority, rule_id);

ALTER TABLE inventory_v2.gateway
  ADD COLUMN IF NOT EXISTS ground_terminal_profile_key text;

ALTER TABLE inventory_v2.target
  ADD COLUMN IF NOT EXISTS ground_terminal_profile_key text;

ALTER TABLE inventory_v2.satellite
  ADD COLUMN IF NOT EXISTS user_beam_profile_key text,
  ADD COLUMN IF NOT EXISTS feeder_beam_profile_key text;

ALTER TABLE inventory_v2.haps
  ADD COLUMN IF NOT EXISTS user_beam_profile_key text,
  ADD COLUMN IF NOT EXISTS feeder_beam_profile_key text;

ALTER TABLE inventory_v2.vsat
  ADD COLUMN IF NOT EXISTS ground_terminal_profile_key text;

ALTER TABLE inventory_v2.theoretical_subscriber
  ADD COLUMN IF NOT EXISTS ground_terminal_profile_key text;

ALTER TABLE inventory_v2.profile_assignment_rule
  ADD COLUMN IF NOT EXISTS region_codes jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS inventory_v2.gateway_catalog_member (
  catalog_id bigint NOT NULL
    REFERENCES inventory_v2.selection_catalog(catalog_id) ON DELETE CASCADE,
  gateway_id bigint NOT NULL
    REFERENCES inventory_v2.gateway(gateway_id) ON DELETE CASCADE,
  ordinal integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (catalog_id, gateway_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_gateway_catalog_member
  ON inventory_v2.gateway_catalog_member(catalog_id, ordinal, gateway_id);

CREATE TABLE IF NOT EXISTS inventory_v2.target_catalog_member (
  catalog_id bigint NOT NULL
    REFERENCES inventory_v2.selection_catalog(catalog_id) ON DELETE CASCADE,
  target_id bigint NOT NULL
    REFERENCES inventory_v2.target(target_id) ON DELETE CASCADE,
  ordinal integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (catalog_id, target_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_target_catalog_member
  ON inventory_v2.target_catalog_member(catalog_id, ordinal, target_id);

CREATE TABLE IF NOT EXISTS inventory_v2.satellite_catalog_member (
  catalog_id bigint NOT NULL
    REFERENCES inventory_v2.selection_catalog(catalog_id) ON DELETE CASCADE,
  satellite_id bigint NOT NULL
    REFERENCES inventory_v2.satellite(satellite_id) ON DELETE CASCADE,
  ordinal integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (catalog_id, satellite_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_satellite_catalog_member
  ON inventory_v2.satellite_catalog_member(catalog_id, ordinal, satellite_id);

CREATE TABLE IF NOT EXISTS inventory_v2.haps_catalog_member (
  catalog_id bigint NOT NULL
    REFERENCES inventory_v2.selection_catalog(catalog_id) ON DELETE CASCADE,
  haps_id bigint NOT NULL
    REFERENCES inventory_v2.haps(haps_id) ON DELETE CASCADE,
  ordinal integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (catalog_id, haps_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_haps_catalog_member
  ON inventory_v2.haps_catalog_member(catalog_id, ordinal, haps_id);

CREATE TABLE IF NOT EXISTS inventory_v2.vsat_catalog_member (
  catalog_id bigint NOT NULL
    REFERENCES inventory_v2.selection_catalog(catalog_id) ON DELETE CASCADE,
  vsat_id bigint NOT NULL
    REFERENCES inventory_v2.vsat(vsat_id) ON DELETE CASCADE,
  ordinal integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (catalog_id, vsat_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_vsat_catalog_member
  ON inventory_v2.vsat_catalog_member(catalog_id, ordinal, vsat_id);

CREATE TABLE IF NOT EXISTS inventory_v2.theoretical_subscriber_catalog_member (
  catalog_id bigint NOT NULL
    REFERENCES inventory_v2.selection_catalog(catalog_id) ON DELETE CASCADE,
  theoretical_subscriber_id bigint NOT NULL
    REFERENCES inventory_v2.theoretical_subscriber(theoretical_subscriber_id) ON DELETE CASCADE,
  ordinal integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (catalog_id, theoretical_subscriber_id)
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_theoretical_subscriber_catalog_member
  ON inventory_v2.theoretical_subscriber_catalog_member(catalog_id, ordinal, theoretical_subscriber_id);

CREATE TABLE IF NOT EXISTS inventory_v2.legacy_inventory_alias (
  kind text NOT NULL,
  legacy_set_key text NOT NULL,
  legacy_external_id text NOT NULL,
  resolved_key text NOT NULL,
  fingerprint_sha1 text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (kind, legacy_set_key, legacy_external_id),
  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers'))
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_legacy_alias_resolved_key
  ON inventory_v2.legacy_inventory_alias(kind, resolved_key);

CREATE TABLE IF NOT EXISTS inventory_v2.selection_profile (
  profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_key text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  source_type text NOT NULL DEFAULT 'manual',
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_selection_profile_active
  ON inventory_v2.selection_profile(is_active, created_at DESC);

CREATE TABLE IF NOT EXISTS inventory_v2.selection_profile_item (
  profile_id bigint NOT NULL
    REFERENCES inventory_v2.selection_profile(profile_id) ON DELETE CASCADE,
  kind text NOT NULL,
  entity_key text NOT NULL,
  ordinal integer NOT NULL DEFAULT 0,
  enabled boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (profile_id, kind, entity_key),
  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers'))
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_selection_profile_item_kind
  ON inventory_v2.selection_profile_item(profile_id, kind, enabled, ordinal, entity_key);

CREATE TABLE IF NOT EXISTS inventory_v2.simulation_request_snapshot (
  snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_key text NOT NULL UNIQUE,
  profile_id bigint
    REFERENCES inventory_v2.selection_profile(profile_id) ON DELETE SET NULL,
  name text NOT NULL,
  source_type text NOT NULL DEFAULT 'manual',
  status text NOT NULL DEFAULT 'created',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),

  CHECK (status IN ('created', 'running', 'finished', 'failed', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_snapshot_profile
  ON inventory_v2.simulation_request_snapshot(profile_id, created_at DESC);

CREATE TABLE IF NOT EXISTS inventory_v2.simulation_request_snapshot_item (
  snapshot_id bigint NOT NULL
    REFERENCES inventory_v2.simulation_request_snapshot(snapshot_id) ON DELETE CASCADE,
  kind text NOT NULL,
  entity_key text NOT NULL,
  ordinal integer NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  PRIMARY KEY (snapshot_id, kind, entity_key),
  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers'))
);

CREATE INDEX IF NOT EXISTS ix_inventory_v2_snapshot_item_kind
  ON inventory_v2.simulation_request_snapshot_item(snapshot_id, kind, ordinal, entity_key);

ALTER TABLE inventory_v2.selection_catalog
  DROP CONSTRAINT IF EXISTS selection_catalog_kind_check;

ALTER TABLE inventory_v2.selection_catalog
  ADD CONSTRAINT selection_catalog_kind_check
  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers'));

ALTER TABLE inventory_v2.legacy_inventory_alias
  DROP CONSTRAINT IF EXISTS legacy_inventory_alias_kind_check;

ALTER TABLE inventory_v2.legacy_inventory_alias
  ADD CONSTRAINT legacy_inventory_alias_kind_check
  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers'));

ALTER TABLE inventory_v2.selection_profile_item
  DROP CONSTRAINT IF EXISTS selection_profile_item_kind_check;

ALTER TABLE inventory_v2.selection_profile_item
  ADD CONSTRAINT selection_profile_item_kind_check
  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers'));

ALTER TABLE inventory_v2.simulation_request_snapshot_item
  DROP CONSTRAINT IF EXISTS simulation_request_snapshot_item_kind_check;

ALTER TABLE inventory_v2.simulation_request_snapshot_item
  ADD CONSTRAINT simulation_request_snapshot_item_kind_check
  CHECK (kind IN ('gateways', 'targets', 'satellites', 'haps', 'vsats', 'theoretical_subscribers'));
